### ISSUE TITLE
Any news on the code?

### ISSUE THREAD

**Issue by fmcarlucci** [shashankkotyan/RobustArchitectureSearch#1]
Hi, we think your paper is really interesting, are you planning to release the code soon?

**Comment by shashankkotyan** [comment]
@fmcarlucci Thank you for your interest in our paper. Apologies for a late reply. We are currently in the process of adding new tests in our paper. We would release the code as soon as we complete the latest tests.

**Comment by shashankkotyan** [comment]
Hi @fmcarlucci, sorry for the late reply. I am glad to know that you find our paper interesting. 

I have added the code in the Repository. In the due time, I will add the comments in the code and also update the Readme file for easier code reading. 

Thank you for your patience.  

As the code is released, I will close this issue.
